---
name: Daniel Fryer
position: "Statistics PhD | Lecturer | Independent consultant"
address: "School of Mathematics and Physics, The University of Queensland"
www: danielvfryer.com
email: daniel@vfryer.com
twitter: _frycast
github: frycast
aboutme: "I'm an early career PhD data scientist, and I'm in the rare position of having combined a rigorous understanding of applied statistics with strong skills in computer science, software engineering, and collaboration on technical projects. I have worked independently, as a researcher, project leader, and software developer, on multiple large exploratory and confirmatory analysis projects, and on research software development projects. I am great at working in messy unprocessed \"big\" data scenarios, involving local and cloud based SQL database management systems. I liase with statisticians, scientists, medical professionals, and executives, and I work with local and international partners, to deliver analysis and preprocessing pipelines that deliver security, confidentiality, interactivity / usability, modularity / reusability, documentation, collaboration, and machine learning / statistical rigour. I have written many private and open source R packages, two of which are currently on CRAN. I teach meta-analysis to Master's students, and I teach database design and SQL programming to professional statisticians and social scientists. I also currently serve as a council member and deputy Communications Officer at the Statistical Society of Australia, as well as technical sub-editor at the Australian & New Zealand Journal of Statistics. In my spare time I enjoy camping, video games, exercise, tasty food, and good conversation."
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)
source("../scripts/setup.R")
```

```{r get data, include=FALSE}
## Presentations
presentations <- read.csv("../data/presentations.csv") %>% 
  dplyr::arrange(dplyr::desc(when))
```


# Education 
```{r}
vitae::detailed_entries(my_education, 
                        when = glue::glue("{start}--{end}"),
                        what = role,
                        where = glue::glue("{city}, {region}, {country}"),
                        with = org,
                        why = dept)
```


# Experience 
```{r}
vitae::detailed_entries(my_employment, 
                        when = glue::glue("{start}--{end}"),
                        what = role,
                        where = glue::glue("{city}, {region}, {country}"),
                        with = org,
                        why = dept)
```

# Service
```{r}
vitae::detailed_entries(my_service, 
                        when = glue::glue("{start}--{end}"),
                        what = role,
                        where = glue::glue("{city}, {region}, {country}"),
                        with = org)
```

# Awards
```{r}
vitae::detailed_entries(my_awards, 
                        when = start,
                        what = glue::glue("{org}, {dept}"),
                        where = glue::glue("{city}, {region}, {country}"),
                        with = role)
```


# Publications

**Pipeline**

```{r}
pubs %>% 
  dplyr::filter(preprint) %>% 
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal, 
    .protect = TRUE
  )
## ORCID version
#vitae::detailed_entries(my_works_preprint, 
#    #with = author,
#    what = title.title.value,
#    when = `publication-date.year.value`,
#    where = `journal-title.value`
#  )
```


**Published**

```{r}
pubs %>% 
  dplyr::filter(first_author, !preprint) %>% 
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal, 
    .protect = TRUE
  )
## ORCID version
#vitae::detailed_entries(my_works_published, 
#    #with = author,
#    what = title.title.value,
#    when = `publication-date.year.value`,
#    where = `journal-title.value`
#  )
```

```{r}
pubs %>% 
  dplyr::filter(!first_author, !preprint) %>% 
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal,
    .protect = TRUE
  )
```

# Presentations and events

```{r}
presentations %>% 
  detailed_entries(what = what,
                   when = when,
                   with = with,
                   where = where,
                   why = why,
                   .protect = TRUE)
```
